bici.yml: Add error message in GA notation

diff --git a/.github/workflows/bici.yml b/.github/workflows/bici.yml
--- a/.github/workflows/bici.yml
+++ b/.github/workflows/bici.yml
@@ -39,7 +39,7 @@ jobs:
         done
 
         if [ $failures -gt 0 ]; then
-          echo "Failed due to missing output files" >&2
+          echo "::error ::Failed due to missing output files" >&2
           exit 1
         else
           echo "All required output files found"
